### ISSUE TITLE
Copy of colleagues assignment gets her/his Urkund address

### ISSUE THREAD

**Issue by peliikt** [danmarsden/moodle-plagiarism_urkund#114]
We have courses where teachers reuse each others activities and among them assignments with Urkund activated. When a teacher import such an activity she/he gets the other teachers Urkund Receiver address instead, this is not a good thing! Shouldn´t this be a personal setting that could not be changed this way?

**Comment by danmarsden** [comment]
Yes - this is expected behaviour. Anyone with teacher or admin access to a course is able to modify the assignment settings including the receiver address in use by the activity. If you believe this should be modified - please get in touch directly with Urkund and discuss further with them.

Thanks!
