### ISSUE TITLE
No plagiarism score 

### ISSUE THREAD

**Issue by ohmoxide** [danmarsden/moodle-plagiarism_urkund#129]
Hello Dan,

Someone at Urkund, maybe Boris, sent me to this Github site to ask you if you know what is going on with our Moodle-Urkund interface.

The problem is hard to describe in words to I made a short screen capture vid and posted it below.

https://youtu.be/-OdeCi4ltPs

Any help you could give would be terrific.

Cheers,
-Rob

**Comment by danmarsden** [comment]
Hey Rob, 

Looks strange! - this doesn't appear to be caused by your urkund integration - looking at the url of the filenotfound error I'd suspect a 3rd party portfolio plugin or some other issue in relation to how your students are selecting the files.

The "grade" page is showing a pdf copy of your students assignment (I assume you have unoconv or google pdf conversion running) but it looks like at some point the access to the original file has gone.

Sorry - can't help much here without further investigation of your system which would require a commercial contract with us, alternatively you could try engaging your local Moodle Partner to help investigate further or if you're looking for free support you could try asking in the community forums on moodle.org to see if anyone else has seen this before.

Good luck!
