### ISSUE TITLE
Urkund settings don't survive backup and restore (in Assignment anyway)

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#39]
I have no idea if this is an Urkund plugin, plagiarism plugins (in general) or Assignment issue. However...

Backup a course with Urkund enabled and restore it. Urkund is now disabled in all Assignments and any settings in the Urkund part of the Assignment configuration are also lost.

**Comment by danmarsden** [comment]
weird - it's supposed to work if you are restoring into the same site. It does prevent the config from restoring into a different site which is probably just a copy over from the Turnitin plugin code as it can't cope with having 2 sites pointing to the same course but URKUND doesn't work that way so that check could probably be removed. If you were trying to restore on the same site there's probably a bug somewhere preventing the config from restoring.

**Comment by thepurpleblob** [comment]
OK - this was a *different* site. All the urkund data is effectively lost, not just the settings.

**Comment by danmarsden** [comment]
Cool - I've just pushed a fix to remove that check - I can't think of a good reason why we preventedthis with URKUND - I probably didn't think about it when I was copying from the Turnitin codebase that I wrote before this one. Allowing this to occur for Turnitin assignments would cause all sorts of nasty stuff....
