### ISSUE TITLE
File not sent to Urkund unless submit is required

### ISSUE THREAD

**Issue by jarmov** [danmarsden/moodle-plagiarism_urkund#45]
When teacher sets the assignment settings so that "**Require students click submit button**" is set to "**No**" and "**When should the file be submitted to URKUND**" is set to "**Submit file when first uploaded**", the file is never sent to Urkund. The file is sent only if, students are required to click the submit button and the file is sent for Urkund after submitting.

I've tried this several times, but can't get it to work. We have Moodle 2.9.2+ (Build: 20150918) and the plugin version is 1.7.6 (2015052100).

![urkund1](https://cloud.githubusercontent.com/assets/15101280/10448087/efb8db36-7192-11e5-84f9-8d078a396312.jpg)
![urkund2](https://cloud.githubusercontent.com/assets/15101280/10448090/f894a474-7192-11e5-83a1-1d310da393e3.jpg)

**Comment by danmarsden** [comment]
Thanks Jarmov, I'll try to take a look at this asap.

**Comment by danmarsden** [comment]
have you checked the admin > plugins > Plagiarism > Urkund > Debugging tab to see if any errors are being reported - particularly about events that are being held up?

**Comment by jarmov** [comment]
Yes, there was one case, where the event was being held up. In that case teacher had used the same setting as I had used in my tests (pictured above). The only difference was, that the teacher had also activated group submissions on the assignment (he had used groups and groupings on the course). 

One student had submitted file for the default group (he didn't belong to any group). For some reason this submission wasn't sent to Urkund and blocked other submissions from going through (except the ones that required students to click "Submit" button at the end). 

I deactivated Urkund for that particular assignment and everything started working again.

**Comment by danmarsden** [comment]
Great - I suspect this was due to the error reported in issue #44 - I've pushed through a patch into the git repository here for this but have not updated the moodle.org plugins database yet. I have a few other incoming improvements within the next 2-3 weeks that should improve things further and I will release them in the plugins database all at once. Thanks for the report!

**Comment by paaskynen** [comment]
Dear Dan,
We have been experiencing a similar problem since the start of October: no files are sent to Urkund from Moodle assignments (nor reports received) regardless of group or submission settings, but the Urkund plugin has continued to work normally in forums. We hope your fix would cure this problem, but it does not yet seem to have been released yet. We use Moodle 2.7.11 and the latest version of the Urkund plugin, 1.7.6 (2015052100).

**Comment by paaskynen** [comment]
P.S. We have a staggering 18 000 events waiting for cron and no easy way to clean these up once the plugin starts working properly again.

**Comment by paaskynen** [comment]
P.S. I applied fix 44 and it seems to have an effect, but I can't confirm yet that it has solved the problem completely.

**Comment by danmarsden** [comment]
Hi @paaskynen - how did you go after applying the patch? - I have one more incoming fix for the next version of URKUND before we release it in the moodle.org plugins db - removing the dependency on the legacy logs system. I am hoping to have that completed (and further testing completed) by the end of next week. So hopefully we should be able to update the plugins db entry in early december. Please let me know if you spot any other issues or if you have any further debugging information if the fix you have applied has not made any significant difference.

thanks,
