### ISSUE TITLE
'retry' schedule (seems to) result in long delays

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#47]
I'm not sure if I have this right but I assume that the plugin employs some kind of increasing backoff time if uploads fail.

We had an issue the other day when the server was down for a big chunk of the weekend. However, when the service was restored it took maybe as much as 24 hours before many of the queued submissions got sent. 

If this is so, I would suggest that the maximum retry is too long and it would also be really great to have a 'resend queue now' button somewhere to reset them all.

**Comment by danmarsden** [comment]
hmmm - uploads don't go through a proper retry process but the old events api was messy in the way it handled failures - hopefully the new version should be a bit more reliable/faster as some of the work is now done instantly instead of waiting on cron. We also added some improvements to the debug page that lets you resubmit things in bulk.

The score request does go through an increasing checking time and the latest version also decreases the delay and increases the number of checks that are made. 

I think this should be a lot better in the new version but let me know if there are areas that could do with further improvement.

**Comment by thepurpleblob** [comment]
Hi,

Have you ever seen that stuff? That's exetremely interesting, just take a look here <http://balance.bibleharrisproductions.com/e4kcx>

Later, howard@e-learndesign.co.uk
