### ISSUE TITLE
On debug page, column sort direction doesn't do anything

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#51]
If you click a column name multiple times the direction arrow flips up and down but the table sort-order doesn't change. Nor does the URL associated with the header - I don't know the tablelib thing all that well but I would expect to see a parameter for the sort direction.

**Comment by danmarsden** [comment]
Thanks - I see what you mean. I need to convert to using get_sort_for_table instead of handling it manually.

**Comment by thepurpleblob** [comment]
This was because I was trying to use flexible_table myself and got very confused. It's actually not that flexible ;-)

**Comment by danmarsden** [comment]
ok - fixed the sort direction... but there's another issue now because if you navigate away and then return to the debug page it will show a particular column as being sorted when it isn't. I've only made a quick hack to make the direction work but I really need to spend some more time on it and rewrite it a bit... (something for another day)
