### ISSUE TITLE
Score (sometimes?) not shown...

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#72]
This is currently a sample of one... but I'm getting twitchy. 

Note... no score shown (all other submissions in this assignment are fine)...

<img width="1029" alt="screen shot 2016-01-08 at 10 44 32" src="https://cloud.githubusercontent.com/assets/664139/12196215/d83e94a4-b5f4-11e5-91da-8cf54cc11eb9.png">

However.....

mysql> select * from mdl_plagiarism_urkund_files where userid=58190\G
*************************** 1. row ***************************
             id: 46943
             cm: 417114
         userid: 58190
     identifier: 07eab859808a1cb3018c08318952774aae6c296c
       filename: 2226113.docx
      reporturl: https://secure.urkund.com/view/...snip....
         optout: https://secure.urkund.com/account/document/exemptionstatus/....snip...
     statuscode: Analyzed
similarityscore: 4
        attempt: 4
  errorresponse: NULL
  timesubmitted: 1452243727
1 row in set (0.00 sec)

So, why is it not shown?

**Comment by thepurpleblob** [comment]
It's no longer a sample of 1. We're seeing several instances of scores not being displayed in Assignment but are in the database table (we actually have a report for assignment that shows the Urkund status so it's quite easy to see).

These are all Assignments that have been created in the last couple of days to replace others that were not working properly.

**Comment by thepurpleblob** [comment]
Students are getting emails (we have established) but cannot see the Urkund link in assignment.

**Comment by lexxkoto** [comment]
Dan, this is Alex Walker. I work at Glasgow University with Howard and I've got some more details on this:

**Steps to Reproduce:**

* Create a new assignment and enable Urkund.
* Log in as a user with permission to edit another user's submission (i.e. site administrator or course manager. I also tried giving this permission to a teacher user with a role on the course, in case that was an issue. It wasn't).
* Edit a student's submission and submit a document.

** Additional Details **

The submission's details will be added to *mdl_plagiarism_urkund_files* as expected. When the originality report comes back, the status code will change to "Analyzed" and the record will be correctly populated with the similarity score, report URL and opt-out link. However, the **URKUND: xx%** text will not appear on the assignment's grading report, and will not be visible when the student views their own submission. It's not a visual (CSS) bug - the text is actually missing from the page entirely.

**Comment by danmarsden** [comment]
thanks - so this is actually a duplicate of #71 and possibly #67 and was an issue with the old version of the code as well. It's likely that Moodle isn't triggering the events (or triggering a completely different event) so the URKUND code doesn't pick it up.

I'm closing this as a duplicate because it relates to user submitting on behalf and we have other issues already open for that. Thanks.

**Comment by thepurpleblob** [comment]
Sorry for random confusion... we get complaints, "my score hasn't appeared" and it sometimes takes a while to figure out what the underlying cause it. But, yes, I would agree... it appears that certain circumstances simply don't trigger the required events.

**Comment by lexxkoto** [comment]
I have a potential fix to lib.php that involves taking out the "check the owning user matches" requirement. I'm not sure if this could introduce any security issues. Someone who knows the assignment system better than me could answer that.

__lib.php line 311:__

`-- $params = array($cmid, $userid, $filehash);`

`++ $params = array($cmid, $filehash);`

__lib.php lines 317-320:__

`-- $plagiarismfile = $DB->get_record_sql(
                    "SELECT * FROM {plagiarism_urkund_files}
                    WHERE cm = ? AND userid = ? AND " .
                    "(identifier = ? ".$extrasql.")", $params);`

`++ $plagiarismfile = $DB->get_record_sql(
                    "SELECT * FROM {plagiarism_urkund_files}
                    WHERE cm = ? AND " .
                    "(identifier = ? ".$extrasql.")", $params);`

**Comment by danmarsden** [comment]
definitely some security issues with that.

Student 1 and Student 2 could submit the same file which would return the same internal contenthash.

In future we could improve the plugin to detect "who submitted first" and then automatically show 100% plagiarised on the 2nd submission without sending it to URKUND for processing. That is what the proof of concept Plagiarism plugin "Moorsp" does at the moment.

It would be better to work out how the userid is not correct. Is it due to the bug we have recently fixed and these are old submissions or is something else occurring - if something else is occurring we need to track that down.

**Comment by thepurpleblob** [comment]
Nope... many have been posted in the last few days.

**Comment by danmarsden** [comment]
I presume the incorrect userid matches the teacher/admin account?

**Comment by lexxkoto** [comment]
It does, yes.

I can see the point about two students submitting the same file to the same assignment, hence using the cmid and user id as identifiers. But it seems like we can't rely on the username being correct here.

I'm wondering if it's viable to use the id field from mdl_assign_submissions instead, since that is stored in the mdl_files table under the itemid field (where the type field is assignsubmission_file). That way, you could search by contenthash and submission id, without it being tied to a particular username.

**Comment by danmarsden** [comment]
no - the userid should be correct, if events are being triggered without the relateduserid being set correctly we need to fix that - and find the conditions that cause it. (I haven't been able to reproduce it yet)

The userid is also used when passing user information to URKUND related to the file - if that isn't correct the user listed when viewing the full report will be incorrect as well.
