### ISSUE TITLE
Submitting on behalf of not working in 3.1

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-plagiarism_urkund#88]
To reproduce...

* Create an Assignment with some users.
* Log in as a teacher or admin and go to the assignment grading screen. Edit  a student's submission and upload a test file
* No cogs appear
* Give it a few minutes and note that an entry for the submission appears in the database table with status 202 (still no cogs)
* In time, the table changes to reflect a score being return but it's still not shown in assignment. 

The user id in the urkund files table is sensible (it is that of the target student). The same Assignment works as expected when logging in as a student and uploading submissions 'normally'

**Comment by danmarsden** [comment]
arg... who uses that submit on behalf thing anyway.... ;-)

...I'll take "another" look at it... maybe one day it will be more stable.....

**Comment by thepurpleblob** [comment]
Yeh, sorry!!    It seems our staff use it all the time. What can one do :-D

**Comment by danmarsden** [comment]
looks like the "easy" option is to keep the plagiarism record using the original userid (admin/teacher) - but this also means that the teacher/admin will get added as the "author" in the urkund report. The Moodle hooks only pass across the file owner and don't pass across any other information that might help us identify the student.

I guess we could add an extra field to the urkund files table that included the "relateduserid" so that when the file is sent it could use the students name but there's a little more work involved there.

**Comment by danmarsden** [comment]
I've just pushed through a patch that stores the relateduserid in a new field and uses that when needed (sending e-mails, attaching user to file sent to turnitin) - let me know if you manage to test it and get it working.

**Comment by thepurpleblob** [comment]
That works now... But... it displays as submitted by the teacher in the debug page.

**Comment by danmarsden** [comment]
ok - I've added some extra text beside the user's name when the file is submitted on behalf for now - I thought about converting it to show the students name but that would throw out the sorting on the page as it will still get sorted by the admins firstname/lastname rather than the students name unless I rewrite the main query to use CASE statements.... which involves a bit more time/effort.... something to look at in future maybe.
