### ISSUE TITLE
'Receiver address' should be mandatory if URKUND is enabled

### ISSUE THREAD

**Issue by pavelsokolov** [danmarsden/moodle-plagiarism_urkund#99]
I think that 'receiver address' should be ruled to be required when 'Enable urkund' is switched to yes, otherwise the error will be thrown when a file is sent to urkund: 'An error occurred trying to send this file to URKUND: No receiver address was specified', in the debug table it's listed with a  444 code.

**Comment by danmarsden** [comment]
from memory it was supposed to disable urkund within an assignment if the receiver address was left blank but maybe something changed to stop that from occurring - thanks for letting us know, makes sense to take a look at this again at some point.

**Comment by danmarsden** [comment]
This should now be fixed in the latest master branch now that we're validating the address properly on save of the module settings form rather than just relying on the ajax warning when it's incorrect.

We have some other changes incoming to the way reciever addresses are handled too - so after the next major release, please let us know if you are still having issues. Thanks!
